### PR TITLE
Adding picture and image sizes

### PR DESCRIPTION
**Pull request by mikeethedude**
This PR does a couple of things. It adds any created image sizes to the size selector when adding an image to a post and it also makes it so images are rendered with a picture element rather than just an img element. There is still work to do, but this gets us to a proof.

### CODE REVIEW

**Comment by mikeethedude** [comment]
This doesn't apply any breakpoints yet but does show the methods we could use to implement the breakpoints and image sizes. If you enter image sizes and run `lando wp media regenerate` it will create images in our sizes as well as the default.

Image sizes should be available in the image size selection when uploading an image in the classic editor and gutenberg.

More work to be done!

**Comment by joetower** [comment]
@mikeethedude This is awesome progress and definitely completes our rock for the quarter, thank you :clap: :clap: 

In functionally testing, I noticed this warning message appears when editing a page: 
`Warning: DOMDocument::loadHTML(): Empty string supplied as input in /app/wp-content/plugins/picture-it/admin/class-picture-it-admin.php on line 637 `

It does not appear to affect anything, but it is there. :smile: 

pi-images

**Comment by mikeethedude** [comment]
Added an issue in #4 to address this warning in the near future.

**Review by joetower — APPROVED** [review]
:+1: :clap: so excited about this!

**Pull request merged**
